server:
  port: 8080
spring:
  datasource:
    # Portu Docker Compose'da 5433 yaptığımız için buraya da 5433 yazıyoruz
    url: jdbc:postgresql://localhost:5433/portfolio_db
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# Güvenlik ve JWT Ayarları
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 saat (ms cinsinden)
# Cloudinary Ayarları
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

app:
  cors:
    # Canlıya çıkarken sunucu panelinden ALLOWED_ORIGINS değerine kendi domainini vereceksin
    # Örn: https://kadirgunduz.com,https://www.kadirgunduz.com
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}

